/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package editTicketInfo;

import javax.swing.JOptionPane;

/**
 *
 * @author 60111
 */
public class editTicket extends javax.swing.JFrame {

    /**
     * Creates new form editTicket
     */
    public editTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        submitButton = new java.awt.Button();
        flightNo = new javax.swing.JTextField();
        departureTime = new javax.swing.JTextField();
        SeatNo = new javax.swing.JTextField();
        arrivalTime = new javax.swing.JTextField();
        passportNo = new javax.swing.JTextField();
        passengerName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setSize(new java.awt.Dimension(1005, 581));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Perpetua", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Edit Ticket Information");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 510, 60));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setText("Flight Number :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 40));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setText("Departure Time:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setText("Arrival Time:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setText("Seat No:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setText("Passenger Name: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setText("Passport No:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        submitButton.setActionCommand("Submit");
        submitButton.setLabel("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, -1, -1));

        flightNo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                flightNoComponentShown(evt);
            }
        });
        flightNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightNoActionPerformed(evt);
            }
        });
        getContentPane().add(flightNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 110, 30));

        departureTime.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                departureTimeComponentShown(evt);
            }
        });
        departureTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureTimeActionPerformed(evt);
            }
        });
        getContentPane().add(departureTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 110, 30));

        SeatNo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                SeatNoComponentShown(evt);
            }
        });
        SeatNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatNoActionPerformed(evt);
            }
        });
        getContentPane().add(SeatNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 110, 30));

        arrivalTime.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                arrivalTimeComponentShown(evt);
            }
        });
        arrivalTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivalTimeActionPerformed(evt);
            }
        });
        getContentPane().add(arrivalTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 110, 30));

        passportNo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                passportNoComponentShown(evt);
            }
        });
        passportNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passportNoActionPerformed(evt);
            }
        });
        getContentPane().add(passportNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 180, 40));

        passengerName.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                passengerNameComponentShown(evt);
            }
        });
        passengerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengerNameActionPerformed(evt);
            }
        });
        getContentPane().add(passengerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/flight.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, -20, 1080, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
    String flightNumber = flightNo.getText();
    String passengerNameStr = passengerName.getText();
    String passportNumber = passportNo.getText();
    
    LinkedListTicketPassengerInfo ticket = new LinkedListTicketPassengerInfo();
    ticket.update(flightNumber, passengerNameStr, passportNumber);
 
    JOptionPane.showMessageDialog(this, "Ticket information updated successfully");
    
    }//GEN-LAST:event_submitButtonActionPerformed

    private void flightNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightNoActionPerformed

    private void SeatNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatNoActionPerformed

    private void departureTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureTimeActionPerformed

    private void arrivalTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivalTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivalTimeActionPerformed

    private void passengerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passengerNameActionPerformed

    private void passportNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passportNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passportNoActionPerformed

    private void flightNoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_flightNoComponentShown
       flightNo.setText("G001");
       flightNo.setEditable(false);
    }//GEN-LAST:event_flightNoComponentShown

    private void SeatNoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_SeatNoComponentShown
        SeatNo.setText("1");
        SeatNo.setEditable(false);
    }//GEN-LAST:event_SeatNoComponentShown

    private void departureTimeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_departureTimeComponentShown
        departureTime.setText("1101");
        departureTime.setEditable(false);
    }//GEN-LAST:event_departureTimeComponentShown

    private void arrivalTimeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_arrivalTimeComponentShown
       arrivalTime.setText("1201");
       arrivalTime.setEditable(false);
    }//GEN-LAST:event_arrivalTimeComponentShown

    private void passengerNameComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_passengerNameComponentShown
        passengerName.setText("Ali");
        passengerName.setEditable(true);
    }//GEN-LAST:event_passengerNameComponentShown

    private void passportNoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_passportNoComponentShown
       passportNo.setText("MY1234");
       passportNo.setEditable(true);
    }//GEN-LAST:event_passportNoComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SeatNo;
    private javax.swing.JTextField arrivalTime;
    private javax.swing.JTextField departureTime;
    private javax.swing.JTextField flightNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField passengerName;
    private javax.swing.JTextField passportNo;
    private java.awt.Button submitButton;
    // End of variables declaration//GEN-END:variables
}
